### ISSUE TITLE
Support Wildcards 

### ISSUE THREAD

**Issue by penguingovernor** [SheetJS/rooster#8]
Currently in rooster to filter any files with similar extensions it would require the user to write out all the extensions by hand like so:

```yaml
- repo: http://svn.apache.org/repos/asf/poi/trunk/test-data/spreadsheet
  type: svn
  extensions:
    - xla
    - xlam
    - xls
    - xlsb
    - xlsm
    - .xlsx
```

This could get tedious if the user is filtering for the same extension across multiple repos.

Rooster should be able to handle wildcards as extensions like so

```yaml
- repo: http://svn.apache.org/repos/asf/poi/trunk/test-data/spreadsheet
  type: svn
  extensions:
    - x*
```
